version: 2.1

workflows:
  version: 2
  test:
    jobs:
      - test-python-3:
          filters:
            branches:
              ignore: master

waitforapt: &waitforapt
  name: Remove cloud init lock
  command: |
      while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo 'Waiting for cloud-init...'; sleep 10; done
      while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do echo 'Waiting for autoupdates to complete...'; sleep 10; done
      echo 'Waiting for instance to really be ready...'
      sleep 30
      sudo rm -rf /var/lib/apt/lists/lock
      sudo rm /var/lib/dpkg/lock && sudo dpkg --configure -a


install_expfactory: &install_expfactory
  name: install expfactory
  command: |
     $HOME/conda/bin/pip uninstall expfactory --yes || echo "Not installed"
     $HOME/conda/bin/python setup.py install

install_python_3: &install_python_3
  name: install Python 3.5 dependencies
  command: | 
      ls $HOME
      if [ ! -d "/home/circleci/conda" ]; then
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
          /bin/bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/conda
          export PATH=$HOME/conda/bin:$PATH
          $HOME/conda/bin/pip install -r requirements.txt
          $HOME/conda/bin/python setup.py install
       else
           echo "Miniconda 3 is already installed, continuing to build."
       fi

install_python_2: &install_python_2
  name: install Python 3.5 dependencies
  command: | 
      ls $HOME
      if [ ! -d "/home/circleci/conda" ]; then
          wget https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh
          /bin/bash Miniconda2-latest-Linux-x86_64.sh -b -p $HOME/conda
          export PATH=$HOME/conda/bin:$PATH
          $HOME/conda/bin/python setup.py install
       else
           echo "Miniconda 2 is already installed, continuing to build."
       fi

test_expfactory: &test_expfactory
  name: Test Experiment Factory (Python 2 and 3)
  command: |
        # We can't test a lot of battery / generation, repo is too big
        cd ~/repo/expfactory/testing
        $HOME/conda/bin/python -m unittest test_experiment
        $HOME/conda/bin/python -m unittest test_battery
        $HOME/conda/bin/python -m unittest test_vm
        $HOME/conda/bin/python -m unittest test_views

jobs:
  test-python-3:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies
      - run: *install_python_3
      - run: *waitforapt
      - run: *install_expfactory
      - save_cache:
          paths:
            - /home/circleci/conda
          key: v1-dependencies        
      - run: *test_expfactory
